### ISSUE TITLE
Could not find the include file "../../partials/examplesHead"

### ISSUE THREAD

**Issue by fullStackRyan** [docusign/code-examples-node#55]
I tried to follow along with the demo on website found here: https://www.youtube.com/watch?v=5iUq00IRaTk&embeds_referring_euri=https%3A%2F%2Fdevelopers.docusign.com%2F&source_ve_path=MzY4NDIsMjg2NjY&feature=emb_logo

It appears that the folder structure is not longer the same for eg001EmbeddedSigning.ejs is no longer in the root. 

I did the quickstart download. 

npm install 

npm start

Then I got the below error

```
Error: C:\Users\RMcAvoy\code\easier-tester-node.js\views\pages\examples\eg001EmbeddedSigning.ejs:1
 >> 1| <%- include("../../partials/examplesHead") %>
    2| 
    3| <%- include("../../partials/exampleInfo") %>
    4| 

Could not find the include file "../../partials/examplesHead"
    at getIncludePath (C:\Users\RMcAvoy\code\easier-tester-node.js\node_modules\ejs\lib\ejs.js:185:13)
    at includeFile (C:\Users\RMcAvoy\code\easier-tester-node.js\node_modules\ejs\lib\ejs.js:311:19)
    at include (C:\Users\RMcAvoy\code\easier-tester-node.js\node_modules\ejs\lib\ejs.js:701:16)
    at eval ("C:\\Users\\RMcAvoy\\code\\easier-tester-node.js\\views\\pages\\examples\\eg001EmbeddedSigning.ejs":10:17)
    at eg001EmbeddedSigning (C:\Users\RMcAvoy\code\easier-tester-node.js\node_modules\ejs\lib\ejs.js:703:17)
    at tryHandleCache (C:\Users\RMcAvoy\code\easier-tester-node.js\node_modules\ejs\lib\ejs.js:274:36)
    at exports.renderFile [as engine] (C:\Users\RMcAvoy\code\easier-tester-node.js\node_modules\ejs\lib\ejs.js:491:10)
    at View.render (C:\Users\RMcAvoy\code\easier-tester-node.js\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\RMcAvoy\code\easier-tester-node.js\node_modules\express\lib\application.js:657:10)
    at Function.render (C:\Users\RMcAvoy\code\easier-tester-node.js\node_modules\express\lib\application.js:609:3)

```

**Comment by InbarGazit** [comment]
This is an issue with the quickstart application that is being fixed tomorrow (🤞 )
You could just clone the whole repo and get the configuration file copied over as a workaround for now

**Comment by InbarGazit** [comment]
Issue is now fixed
